language: php
cache:
  directories:
    - src/node_modules
    - $HOME/src/.composer/cache
    - src/vendor
    
dist: trusty

sudo: required

services:
  - mysql

php:
  - '7.0'
  - '7.1'

env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

before_install:
  - cd src
  - composer self-update
  - npm install -g webpack@1.X -g

install:
  - composer install
  - npm install
  - webpack
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test

script:
  - ./vendor/bin/simple-phpunit
