version: '2'
services:
    db:
        image: mysql
        restart: always
        ports:
            - "13306:3306"
        volumes:
            - ./docker/mysql/:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./docker/php-dev
        restart: always
        volumes:
            - ./src:/code
        links:
            - db
    nginx:
        build: ./docker/nginx
        restart: always
        ports:
            - "18080:80"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        links:
            - php