version: '2'

services:
  composer:
    image: composer/composer:1.1-alpine
    volumes:
      - ./src:/app
  phpunit:
    image: phpunit/phpunit:5.7.5
    volumes:
      - ./src:/app
    command: [""]
  webpack:
    build: ./docker/node
    volumes:
      - ./src:/app
    entrypoint: ["webpack"]
  npm:
    build: ./docker/node
    volumes:
      - ./src:/app
    entrypoint: ["npm"]
