homepage:
    path:     /
    defaults: { _controller: IITAllSpeakBundle:Default:index }

survey:
    path:     /survey
    defaults: { _controller: IITAllSpeakBundle:Default:survey }

login:
    path:     /login
    defaults: { _controller: IITAllSpeakBundle:Security:login }

logout:
    path:     /logout

