IIT\AllSpeakBundle\Entity\SurveyAnswer:
    properties:
        ts:
            - NotNull:
        gender:
            - Choice:
                choices:  [M, F]
                message:  surveyAnswer.gender.notvalid
                strict: true
        birthYear:
            - Range:
                  min: 1940
                  max: 2050
                  minMessage: surveyAnswer.birthYear.belowLimit
                  maxMessage: surveyAnswer.birthYear.aboveLimit
        diagnosisDate:
            - Date: ~
        alsfrsr:
            - NotNull:
                message: surveyAnswer.alsfrsr.empty
            - Range:
                  min: 0
                  max: 40
                  minMessage: surveyAnswer.alsfrsr.belowLimit
                  maxMessage: surveyAnswer.alsfrsr.aboveLimit
        communicationFunction:
            - NotNull:
                message: surveyAnswer.communicativeFunction.empty
            - Range:
                  min: 0
                  max: 4
                  minMessage: surveyAnswer.communicativeFunction.belowLimit
                  maxMessage: surveyAnswer.communicativeFunction.overLimit
        diagnosis:
            - Choice:
                choices:  [S, B]
                message:  surveyAnswer.diagnosis.notValid
                strict: true
        sentences:
            - Count:
                  min: 1
                  max: 10
                  minMessage: surveyAnswer.sentences.belowLimit
                  maxMessage: surveyAnswer.sentences.aboveLimit