IIT\AllSpeakBundle\Entity\SurveyAnswer:
    properties:
        ts:
            - NotNull:
        gender:
            - Choice:
                choices:  [M, F]
                message:  Genere non valido
                strict: true
        birthYear:
            - Range:
                  min: 1940
                  max: 2050
                  minMessage: L'anno di nascita dev'essere maggiore di {{ limit }}
                  maxMessage: L'anno di nascita dev'essere minore dell'anno corrente
        diagnosisDate:
            - Date: ~
        alsfrsr:
            - NotNull:
                message: Il campo alsfrs-r non puo' essere lasciato vuoto
            - Range:
                  min: 0
                  max: 40
                  minMessage: L'alsfrs-r dev'essere maggiore o uguale a {{ limit }}
                  maxMessage: L'alsfrs-r dev'essere minore o uguale a {{ limit }}
        communicationFunction:
            - NotNull:
                message: Il campo funzione comunicativa non puo' essere lasciato vuoto
            - Range:
                  min: 0
                  max: 4
                  minMessage: Il valore del campo funzione comunicativa dev'essere maggiore o uguale a {{ limit }}
                  maxMessage: Il valore del campo funzione comunicativa dev'essere minore o uguale a {{ limit }}
        diagnosis:
            - Choice:
                choices:  [S, B]
                message:  Diagnosi non valida
                strict: true
        sentences:
            - Count:
                  min: 1
                  max: 10
                  minMessage: E' necessario specificare almeno una frase
                  maxMessage: Non e' possibile specificare piu' di {{ limit }} frasi