<?php

namespace IIT\AllSpeakBundle\Repository;

/**
 * SurveyAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
