<?php

namespace IIT\AllSpeakBundle\Repository;

/**
 * SurveySentenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveySentenceRepository extends \Doctrine\ORM\EntityRepository
{
}
