# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    access_denied_url: /login

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    surveytaker:
                        password: "%surveytaker_password%"
                        roles: 'ROLE_SURVEYTAKER'
                    admin:
                        password: "%admin_password%"
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        survey:
            pattern: ^/%languages%/survey
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: survey_login
                check_path: survey_login

            logout:
                path: /en/survey_logout
                target: /
                invalidate_session: false

            context: primary_auth

        admin:
            pattern: ^/
            anonymous: ~

            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /
                invalidate_session: false

            context: primary_auth

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/%languages%/survey$, roles: ROLE_SURVEYTAKER }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_SURVEYTAKER