# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    surveytaker:
                        password: "%surveytaker_password%"
                        roles: 'ROLE_SURVEYTAKER'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        survey:
            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
                login_path: survey_login
                check_path: survey_login

            logout:
                path: /logout
                target: /
                invalidate_session: false

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/survey$, roles: ROLE_SURVEYTAKER }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext