IIT\AllSpeakBundle\Entity\SurveySentence:
    type: entity
    table: null
    repositoryClass: IIT\AllSpeakBundle\Repository\SurveySentenceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        itText:
            type: string
            length: 255
            nullable: true
        enText:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
